name: Static Publication

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: "./docs"
          GH_PAT: ${{ secrets.STATIC_DEPLOY_KEY }}
